module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/BWc4IFWihyN97JDPdHWUIZ?mode=ac_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/j89qv8.jpg',
    NEWSLETTER_JID: '120363399707841760@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'SANCHO-XMD MINI,
    OWNER_NAME: 'SANCHO-TECH,
    OWNER_NUMBER: '263780325289',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © POWERED BY SANCHO TECH,
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbARanh0LKZI3sZO0g20,
};
